### ISSUE TITLE
Bottom (horizontal) window divider not showing

### ISSUE THREAD

**Issue by jamiecollinson** [tautologyclub/feebleline#10]
I suspect this isn't a feebleline thing but is probably something to do with `window-divider-mode` but I'm hoping you might be able to help.

I'm using GNU Emacs 25.3.1 on MacOS, and I've installed with:

```
(use-package feebleline
  :ensure t)
```

And I have vertical border between horizontal windows, but not a horizontal divider between vertical ones:

<img width="580" alt="screen shot 2018-02-26 at 18 37 13" src="https://user-images.githubusercontent.com/3263722/36689478-6d9d4506-1b27-11e8-9a76-67f420762aeb.png">

`window-divider-mode` is on (presumably enabled by `feebleline`) and I've tried playing around with the `window-divider-default-bottom-width`, `window-divider-default-places` to no avail. Weirdly I see the vertical border regardless of the state of `window-divider-mode`, so perhaps there's another way to draw the borders I'm not aware of. It also doesn't seem to matter which theme I select, as I thought perhaps it was a bad `face` definition.

Love how `feebleline` looks so really hoping I can figure this out!

**Comment by tautologyclub** [comment]
Hi sorry for the late reply, github wasn't notifying me of the issue for some reason. If you're on terminal emacs you should just disable window-divider-mode altogether. It's basically a GUI only feature.

**Comment by jamiecollinson** [comment]
No problem and appreciate you replying. My screenshot is probably confusing but I'm on the gui version of gnu emacs (https://emacsformacosx.com).

Completely understand it's not your problem, but any suggestions welcome - I'd love to use feeblline but really need some sort of divider or things are too confusing!

**Comment by tautologyclub** [comment]
It's kinda sorta my problem, I like it when people enjoy something I've done. I'll try to sniff around.

**Comment by tautologyclub** [comment]
Sorry for the late reply again, but if you want you can try (setq feebleline-use-legacy-settings t) and then toggle feebline-mode off/on. This is the kind of situation I put that setting in there for. If this doesn't work I'd suspect it's just a bug in window-divider-mode. It's a new feature so it's probably a bit untested on non-linux systems. Which is sort of good news, because it's likely to get fixed soon enough.

**Comment by jamiecollinson** [comment]
Thanks! With `(setq feebleline-use-legacy-settings t)` I'm getting what I believe is the correct behaviour based on your screenshots:

<img width="579" alt="screen shot 2018-03-24 at 12 14 19" src="https://user-images.githubusercontent.com/3263722/37863852-2e21ac4c-2f5d-11e8-8e4a-770706a6e15b.png">

There seem to be some display glitches in the horizontal dividers still, so I'll have a play with the `window-divider-mode` variables and see if that helps.

**Comment by jamiecollinson** [comment]
Just read your code and see that with legacy mode that's just a really small mode line - what I thought was a glitch is the mode line rendering. Changing the active style should fix my issue I guess.

**Comment by jamiecollinson** [comment]
Just a note for any future readers using `feebleline-use-legacy-settings`. Customising the mode line faces a little gives a good effect:

<img width="580" alt="screen shot 2018-03-24 at 12 33 49" src="https://user-images.githubusercontent.com/3263722/37863989-d16bc9bc-2f5f-11e8-9055-0b794b03bee2.png">

I guess it'll be theme dependent, but with my dark theme this worked well:

```emacs-lisp
(custom-set-faces
 '(mode-line ((t (:height 0.1 :background "grey75" :foreground "grey75"))))
 '(mode-line-inactive ((t (:height 0.1 :background "grey25" :foreground "grey25"))))
 )
```

@tautologyclub was going to raise a pull request to suggest adding them to https://github.com/tautologyclub/feebleline/blob/master/feebleline.el#L120, but not sure you'd want that?

**Comment by tautologyclub** [comment]
Since your fix is only applicable to people using specifically 

* a dark theme 
* a dark modeline
* an emacs that doesn't have proper support for window-divider-mode

I think it's a little slim. But I'm happy to hear the fix worked out nicely for you!
