### ISSUE TITLE
[Feature-request] hide-show original mode-line

### ISSUE THREAD

**Issue by Dickby** [tautologyclub/feebleline#11]
Hi, it would be nice if enabling feebleline-mode would set the `mode-line-format` to nil and disabling restores the old format.
Thanks

**Comment by tautologyclub** [comment]
Hi, that's what it's supposed to do :) it does for me at least. What happens when you toggle feebleline-mode?

**Comment by Dickby** [comment]
Your right, it seems to be my configuration with `emacs -Q` i get the right behaviour.
I will see what causes the problem in my configuration and report it here if i think it should be considered.
Closing this.
Thanks
