### ISSUE TITLE
mode line not changed in all visible windows

### ISSUE THREAD

**Issue by Dickby** [tautologyclub/feebleline#17]
toggling feebleline-mode should change the mode-line of every visible window.
At the moment only the active window's mode-line is changed.

**Comment by tautologyclub** [comment]
No I'm pretty sure this isn't the case. Feebleline is global.

**Comment by tautologyclub** [comment]
Aha now I see what you mean. Yeah I guess I didn't pay much attention to toggling because I never turn it off. Ok.

**Comment by tautologyclub** [comment]
Merged your commit, thanks for the feedback and contribution :)
