### ISSUE TITLE
plan for melpa?

### ISSUE THREAD

**Issue by gongzhitaao** [tautologyclub/feebleline#2]
Quick question: any plan for submitting to MELPA?

**Comment by danlamanna** [comment]
+1

**Comment by tautologyclub** [comment]
For some reason github isn't sending me e-mail notifications, so I haven't noticed any activity here. I'll just brush up the code and then I'll check out the wiki on how to submit to melpa, alright?

**Comment by tautologyclub** [comment]
I have submitted it to melpa. Hopefully y'all will enjoy it even with the new code changes.

**Comment by tautologyclub** [comment]
Accepted! :) thanks for the push, guys.
