### ISSUE TITLE
`git` branch display doesn't work on tramp-mode

### ISSUE THREAD

**Issue by vishesh** [tautologyclub/feebleline#23]
The git branch display doesn't work when working on a remote git repository using Tramp mode. Instead of showing branch it displays error like this: `cd: no such file or directory: /ssh:user@host:/path/to/file`

I think code over here[1] needs to be more clever. Not sure how other plugins work with Tramp, but most other things (like vc-mode, magit) work. Maybe we can reuse something from vc-mode to identify the repository branch? That way it can also work other version control systems as well.

[1] https://github.com/tautologyclub/feebleline/blob/master/feebleline.el#L124

**Comment by tautologyclub** [comment]
Aha I never use tramp (I like sshfs) but that snippet is terrible :D 

If we're fine requiring magit, then this will do it for you:

```
(defun feebleline--git-branch-string ()
  "Return current git branch as a string, or the empty string if pwd is not in a git repo (or the git command is not found)."
  (interactive)
  (require 'esh-ext)
  (let ((git-output (magit-get-current-branch)))
    (if (> (length git-output) 0)
        git-output
      "(no branch)")))
```

Not sure what common practice is regarding requiring third party packages is, so I made the defun itself conditional. Gonna test it out before I push.

**Comment by tautologyclub** [comment]
Pushed, feel free to try it out.

**Comment by vishesh** [comment]
Awesome, I will try it out after work. I love Magit, so I'm totally cool with requiring it.

Couple more suggestions:

1. If I'm not mistaken, we fallback to old implementation if magit isn't there. In that case maybe, handle errors when `cd` or `git` fails.
2. If we are not in a repository, we output "(no branch)". I think it should be ok to ignore that. vc-mode in emacs, zsh git plugin, and vim's airline all skip any output in case there is no branch. One advantage is that, if it actually is a repo that is not supported by magit, we won't have a wrong branch name in the line.

**Comment by tautologyclub** [comment]
Those are super minor tweaks, I'm sure you can make a PR out of them.
