### ISSUE TITLE
Horizontal border in terminal?

### ISSUE THREAD

**Issue by kevinboulain** [tautologyclub/feebleline#24]
Hi there,

Since the mode line seems to be the go-to horizontal separator between buffers, when feebleline is active there isn't much visual clues to know where a buffer ends and where another starts.
Vertically, everything is fine since there is the vertical border.

It's probably related to #10 but since my Emacs is always started from a terminal, I can't seem to rely on `window-divider-mode`.

I attach some screenshots to better to showcase the problem.

First, the `*scratch*` buffer with a vertical split (I wrote some stuff in the buffers as an explanation):
<img width="1920" alt="screen shot 2018-09-30 at 17 49 07" src="https://user-images.githubusercontent.com/3048933/46259492-7898e200-c4da-11e8-940b-8bb8e556b0f5.png">

Then I split the left window horizontally and open `/tmp/feebleline.txt`:
<img width="1920" alt="screen shot 2018-09-30 at 17 54 45" src="https://user-images.githubusercontent.com/3048933/46259525-d62d2e80-c4da-11e8-9297-e89fb7e3c88f.png">

Notice that due to `mode-line-format` being buffer-local, I can't seem to get rid of the right mode line activated by the top left window (since I want a visual separator between `*scratch*` and `/tmp/feebleline.txt`.

Of course, I could somehow cheat with line numbers and convince myself it's enough of a visual clue but it's bit cumbersome when the number have similar digits (even more for multiple horizontal splits):
<img width="1920" alt="screen shot 2018-09-30 at 18 20 43" src="https://user-images.githubusercontent.com/3048933/46259751-9ddb1f80-c4dd-11e8-88ac-1bb8c1ebb023.png">

Do you see any way to solve this small issue? I'm sure I can live with it but well, if I could make it perfect... :)
Or maybe I should dim the inactive windows (but it's probably a bit hard to make it play well with all themes out of the box?).

By the way, here is the Elisp hack shown in the first two screenshots, sorry for my awful Emacs-fu :)
```elisp
(add-hook 'window-configuration-change-hook
          (lambda ()
            (when (bound-and-true-p feebleline-mode)
              (walk-windows (lambda (window) ; reset the mode line of each buffer
                              (with-current-buffer (window-buffer window)
                                (setq mode-line-format nil)))
                            0) ; don't include minibuffer
              (walk-windows (lambda (window) ; and set the mode line when necessary
                              (with-current-buffer (window-buffer window)
                                ;; {frame,window}-edges functions return (x1 y1 x2 y2)
                                ;; then check if the current buffer (which may be displayed on mutltiple windows)
                                ;; doesn't sit on top of the minibuffer
                                ;; this isn't perfect but unfortunately, the mode-line-format is buffer-local
                                (when (/= (nth 1 (window-edges (minibuffer-window)))
                                          (nth 3 (window-edges window)))
                                  (setq mode-line-format "%-"))))
                            0))))) ; don't include minibuffer
```
The idea is simple: use a dumbed down mode line as an horizontal separator if and only if a window doesn't sit on top of the minibuffer.

Thanks for the package :)

Regards.

**Comment by fth86** [comment]
Ether42, I was looking into doing the exact same thing just an hour after you
made that post. I came up with this:

```lisp
(defun fn--hide-modeline-selectively ()
  (when (bound-and-true-p feebleline-mode)
	(let ((buffers-at-bottom '())
	       (buffers-at-top '()))
	  (walk-windows (lambda (window)
			           (with-current-buffer (window-buffer window)
				       (if (eq (frame-height)
						 (+ (car (last (window-edges window))) 1))
						(add-to-list 'buffers-at-bottom (current-buffer))
				              (add-to-list 'buffers-at-top (current-buffer)))))
					0)

	  (loop for buf in (cl-set-difference buffers-at-bottom buffers-at-top)
			do (with-current-buffer buf
				 (setq mode-line-format nil)))

	  (loop for buf in buffers-at-top
			do (with-current-buffer buf
				 (setq mode-line-format ".")))))
  )
(add-hook 'window-configuration-change-hook #'fn--hide-modeline-selectively)
```

Works fine.

**Comment by kevinboulain** [comment]
@fth86 it looks like your code has the issue shown in the second screenshot: since `mode-line-format` is buffer-local you may display a mode line when not strictly required (but only showing a small symbol doesn't bother that much I guess, I may steal the idea).

**EDIT**: adding/subtracting 1 was my first approach but it doesn't always work (for example if the minibuffer shows more than one line).

**Comment by tautologyclub** [comment]
I have to admit I have no clue what you guys are talking about. I'm not even sure what the desired behaviour is. Your problem is that `mode-line` doesn't retain its height set by `set-face-attribute` when you create a new window? If so, couldn't you just use `custom-set-faces` or something instead of `set-face-attribute` inside `feebleline-legacy-settings-on`? I guess I'm not understanding the question right though...

**Comment by kevinboulain** [comment]
I'm not sure I can explain it better than "we want an horizontal mode-line between buffers to separate them but not at the bottom (between a buffer and the minibuffer) because it wastes a line in the terminal and is now unnecessary with feebleline".
Compare last line of bottom left window (empty) and bottom right window (`mode-line-format "%-"`) of the second screenshot, above the minibuffer/feebleline.

From what I understand, #10 works by making the mode-line a 1 pixel height line (so it will be displayed both between two buffers and between a buffer and the minibuffer), which is fine. However, in a terminal, it's not possible to cheat by using a 1 pixel mode-line so you have to use a full-height line (which feels wasteful and not that much useful once you activate feebleline).

**Comment by endian-benjamin** [comment]
The only thing I can recommend is something like auto-dim-other-buffers-mode.

**Comment by kevinboulain** [comment]
auto-dim-other-buffers has the same problem: https://github.com/mina86/auto-dim-other-buffers.el/issues/16.
I guess I should close this issue as it's not strictly related to feebleline and there doesn't seem to be a solution for now.
