### ISSUE TITLE
List of 'recipes' for feebleline-mode-text?

### ISSUE THREAD

**Issue by kevinboulain** [tautologyclub/feebleline#25]
It's nice that `feebleline-mode-text` is easily customizable, but shouldn't it be built on some kind of list of functions and modifiers for easier modification?

Actually, it seems the way to edit/extend is to simply copy/paste it into your Emacs configuration and add or remove some parts of it.
Should the format be revised to allow people to make pull requests to your repository and add some functions that add more information (without necessarily adding them to the default value)?

For example, if I want to make a pull request to add [Circe](https://github.com/jorgenschaefer/circe) support so others don't have to find their way around, I would have to append it to the list and it will continue to grow and may be difficult to get it right (for example, the fact that I didn't want some spaces between some of the information require to copy most of the definitions, see for example the colon between the file and the git branch in #24 which differs from the default value). Also, since I have to redefine the whole variable, I can't even use some of the definitions from your repository.

Screenshot for the Circe support:
<img width="1920" alt="screen shot 2018-09-30 at 18 38 38" src="https://user-images.githubusercontent.com/3048933/46259998-f5c75580-c4e0-11e8-9d8a-70e6055c1837.png">
You can see some some channels:
- I'm actually visiting `#bla` so it's marked like a standard buffer 
- I have been highlighted in `#blu` so I took the asterisk face you have setup and appended it to the channel's name
- `#bli` has some discussion in it but there is nothing special (no highlight) so it's a bit more dim
- other channels are not listed for concision since there isn't any activity in them

Off the top of my head (I'm no Elisp expert so take it with a grain of salt), here is a proposition that could probably resolve this issue and ease contributions and customization (not tested, so may contain typos):
```elisp
(setq feebleline-mode-line-text
      '(;; after would optionally add the space if something after it evaluate to a non-empty string
        (line-and-column-number :face feebleline-linum-face :after " ")
        ;; before (I lack a better name) is tricky, but should have some mechanism to places its string before the previous :after property?
        (buffer-name :face feebleline-dir-face :after " ")
        ;; when the function may return nothing, simply ignore before/after properties
        (git-branch :face feebleline-git-branch-face :before ":" :after " ")
        ;; no special face because it will use multiple ones for the same string
        (circe-channels)))
```
Thanks!

**Comment by kevinboulain** [comment]
By the way, it's easy to see how it could please some people.
If I take for example the line and column numbers (a bit overkill, but still a good example), feebleline could simply expose two functions (one to get the line number and another one to get the column number) and use some modifiers to join them. If the user doesn't care about the column number or doesn't like the way it's displayed, (s)he simply has to remove the function call or modify the before/after/whatever properties in its configuration (still some copy/pasting but more maintainable).

For the record, maybe feebleline should check for `line-number-mode` & `column-number-mode` instead of hardcoding them? So it would have the same behavior as the mode line.

**Comment by tautologyclub** [comment]
Was looking at how the component customization is handled just the other day actually, yeah it's pretty poorly handled. I think attributes, especially `:face` would de-uglify things a little bit. You could even allow something like `:format "%-3s"`. But I don't agree wholeheartedly about your point -- why couldn't you append elements to feebleline-mode-line-text without redefining the whole variable?

That small remark aside, I do think making the format of the variable less ugly is a very worthy objective and your proposal is probably the sanest way to do it.

I have one idea for improvement however: split `feebleline-mode-line-text` into separate lists:

```[  left-most | main | just-right-of-main | right-aligned  ]```

then you could append/prepend to whatever part you wanted. Thoughts?

**Comment by tautologyclub** [comment]
On second thought, I'm not sure you can use `:keywords` like that... The emacs wiki mentions keyword ARGUMENTS (https://www.emacswiki.org/emacs/KeywordArguments). I can't recall seeing them anywhere other than as arguments to functions. But I guess that conceptually having `feebleline-mode-line-text` be a list of lists with format:

```
(function-name key-value-list)
```

where `key-value-list` is either omitted something like 

```
((face   . some-face)
 (pre    . ":")
 (post   . "/")
 (format . "%3s")
)
```

and obviously the keys default to reasonable values (`pre = "", post = " ", format = "%s"` etc).

I realize this would make customizations slightly less elegant than `:attribute value` but... yeah.

**Comment by tautologyclub** [comment]
I have a preliminary demo if anyone wants to try it out, it's in the development branch right now. You have to clone, then open feebleline-test.el and evaluate buffer. Turn off feebleline-mode first though because they will obviously conflict.

`feebleline-msgfunctions` can be just a list of (list of) functions, with optional property alists, for example:

```
(setq
 feebleline-msg-functions
 '((my-own-linecol-string)    ;; note -- no properties
   (buffer-file-name          ((face . feebleline-dir-face) (post . "")))
   ((lambda () ":")           ((post . "")))
   (magit-get-current-branch  ((face . font-lock-comment-face)))
   ((lambda () "some string"))))
```

EDIT: Note that there are many ways to wrap the slightly ugly alist syntax to make it very similar to what @ether42 was suggesting. I.e. something like  

```
(defun feebleline-add-component (function-name &optional position &key face pre post)
...
)
```

**Comment by kevinboulain** [comment]
I'm no Elisp expert, but doesn't this example handle keywords?
```elisp
(defun after-space ()
  "Simply return a space, useful as link between formatters."
  " ")

(defun append-empty ()
  "Nothing to append by default."
  "")

(defun prepend-empty ()
  "Nothing to prepend by default."
  "")

(defun append-asterisk ()
  "Append asterisk."
  (propertize "*" 'face 'feebleline-asterisk-face))

(defun formatter-hello-world ()
  "Simplest example of a formatter."
  "hello world")

(defun formatter-git-branch ()
  "Return current git branch."
  (propertize
   (if (fboundp 'magit-get-current-branch)
       (magit-get-current-branch)
     "")
   'face 'feebleline-git-branch-face))

(defun formatter-buffer-name ()
  "Return the buffer name."
  (propertize
   (if (buffer-file-name)
       (let ((directory (replace-regexp-in-string (regexp-quote (expand-file-name "~")) "~" (file-name-directory (buffer-file-name))))
             (filename (file-name-nondirectory (buffer-file-name))))
         (concat directory filename))
     (buffer-name))
   'face 'feebleline-bufname-face))

(defun formatter-append-modified-buffer ()
  "Indicator of a modified buffer."
  (if (buffer-modified-p) (append-asterisk) ""))

(cl-defun apply-formatter (formatter
                           &key
                           (prepend 'prepend-empty)
                           (append 'append-empty)
                           (after 'after-space))
  "To be fleshed out."
  (string-join (mapcar (lambda (f) (if f (funcall f) "")) (list prepend formatter append after))))

(defun example ()
  ""
  (interactive)
  (message "%s" (string-join
                 (mapcar (lambda (arguments) (apply 'apply-formatter arguments))
                         ;; example of user definition
                         '((formatter-hello-world)
                           (formatter-buffer-name :append formatter-append-modified-buffer :after nil)
                           (formatter-git-branch :prepend (lambda () ":")))))))
```

`M-x example` will output `hello world ~/Documents/git/dotfiles/bla.el*:tmp`.

Will checkout your branch later, thanks!

**EDIT**: re "why couldn't you append elements to feebleline-mode-line-text without redefining the whole variable?" That's probably some corner case, but if the user want to redefine the order/remove an element/change a specific (like I did), he probably will have to redefine everything. But I agree that most of time, simply appending should be ok.

**Comment by tautologyclub** [comment]
I can't see how you'd use your example for customizing a variable using `:keywords`. In fact, that looks way worse than it is in its current state :P

**Comment by kevinboulain** [comment]
The user would have to set the format with:
```elisp
(setq feebleline-mode-line-text '(
  (formatter-hello-world)
  (formatter-buffer-name :append formatter-append-modified-buffer :after nil)
  (formatter-git-branch :prepend (lambda () ":"))
))
```

I admit the ` :prepend (lambda () ":")` is way too verbose, but it's probably possible to check if it's a callable and if it is, evaluate, else use it directly as a string, which would give:
```elisp
(setq feebleline-mode-line-text '(
  (formatter-hello-world)
  (formatter-buffer-name :append "*" :after nil) ; user doesn't want a face on the asterisk
  (formatter-git-branch :prepend " : " :face 'feebleline-git-branch-face) ; user simply want spaces between branch and buffer
))
```

See the list in the `example` function. I should probably have passed it/set a global for clarity, everything else is boilerplate to get a minimal working example.

---

For the record, here is what I do in my configuration:
```elisp
;; ...

  ;; mainly from feebleline.el, but more minimalistic
  ;; note there is a timer, so not everything will be instantaneously refreshed
  (setq feebleline-mode-line-text
        '(("%s" ((let ((indicator (string-join
                                   (-keep (lambda (pair) (when (car pair) (cdr pair)))
                                          (list (cons (bound-and-true-p line-number-mode) (format-mode-line "%l"))
                                                (cons (bound-and-true-p column-number-mode) (number-to-string (current-column)))))
                                   ",")))
                   (if (> (length indicator) 0) (concat indicator " ") "")))
           (face feebleline-linum-face))
          ("%s" ((if (buffer-file-name)
                     (replace-regexp-in-string
                      feebleline--home-dir "~"
                      (file-name-directory (buffer-file-name)))
                   ""))
           (face feebleline-dir-face))
          ("%s" ((if (buffer-file-name)
                     (file-name-nondirectory (buffer-file-name))
                   (buffer-name)))
           (face feebleline-bufname-face))
          ("%s" ((if (and (buffer-file-name) (buffer-modified-p))
                     "*"
                   ""))
           (face feebleline-asterisk-face))
          ("%s" ((if (fboundp 'magit-get-current-branch) ; set by magit
                     (let ((branch (magit-get-current-branch)))
                       (if (> (length branch) 0) (concat ":" branch) ""))
                   ""))
           (face feebleline-git-branch-face))
          ("%s" ; for circe, display the list of active buffers
           ((if (boundp 'tracking-buffers) ; set by circe
                (concat " " (string-join
                             (mapcar (lambda (buffer)
                                       (let ((propertized-buffer (propertize buffer 'face 'feebleline-previous-buffer-face))) ; change the face
                                         (if (eq (get-text-property 0 'face buffer) 'circe-highlight-nick-face) ; when highlighted
                                             (concat propertized-buffer (propertize "*" 'face 'feebleline-asterisk-face)) ; append a feebleline asterisk
                                           propertized-buffer)))
                                     tracking-buffers) ; for each buffer
                             " "))
              "")))))

;; ...
```

**Comment by tautologyclub** [comment]
So... you've actually tested

```
(setq feebleline-mode-line-text '(
  (formatter-hello-world)
  (formatter-buffer-name :append formatter-append-modified-buffer :after nil)
  (formatter-git-branch :prepend (lambda () ":"))
))
```

and verified that it's acceptable syntax?

**Comment by kevinboulain** [comment]
Hm, yeah, paste the above code in a file and make Emacs evaluate it with `M-x eval-buffer`.
Then just do `M-x example` (or call if from `ielm` if you want to experiment), which will `apply` the list with the keywords in it and give them to `apply-formatter`.
You should see the result in the minibuffer.

The only things to do seem to be:
 - use `apply`
 - use `cl-define` with `&key` (and probably define some sane defaults to avoid nil-checking)

**Comment by tautologyclub** [comment]
Yeah I should have just tested it. I see now that `(setq my-list '(blabla :keyword value))` works syntactically. TIL!

EDIT: You don't need all that machinery though, it'll work fine with some simple modifications to what's already in feebleline-test.el.

**Comment by kevinboulain** [comment]
Thanks for your patience :)

**EDIT**: yeah I know, it was a bit verbose but that was to get a contained/reproducible example without me needing to copy/paste from feebleline. I saw in the develop branch you export a bunch of functions that should remove the need of all this definitions.

**Comment by tautologyclub** [comment]
Hey again,

I reworked it and moves the improvements to `feebleline.el`, so just clone the development branch and feel free to play around with it. All string-returning functions can now be used, even lambda functions. If function returns nil, nothing is messaged (including pre and post). Still no `:keywords`, but they're planned if I ever get around to it,
