### ISSUE TITLE
With new update nothing is shown

### ISSUE THREAD

**Issue by ghost** [tautologyclub/feebleline#36]
Hey,

I just have updated the feebleline. I am using the new configuration (from the readme):

(use-package    feebleline
  :ensure       t
  :config       (setq feebleline-msg-functions
                      '((feebleline-line-number         :post "" :fmt "%5s")
                        (feebleline-column-number       :pre ":" :fmt "%-2s")
                        (feebleline-file-directory      :face feebleline-dir-face :post "")
                        (feebleline-file-or-buffer-name :face font-lock-keyword-face :post "")
                        (feebleline-file-modified-star  :face font-lock-warning-face :post "")
                        (feebleline-git-branch          :face feebleline-git-face :pre " : ")
                        (feebleline-project-name        :align right)))
  (feebleline-mode 1))

feebleline mode is enabled. However nothing is shown in minibuffer. Could you help me to find what is the problem.

**Comment by kevinboulain** [comment]
It seems errors are now ignored, you probably have a backtrace that is caught.
Try to comment some of the 'heavy' functions to pinpoint the crashing one (like git, project, etc). You can also evaluate the functions directly with `M-x` and see if they work correctly.

**Comment by ghost** [comment]
Yeah, Thank you. i found that i have problems with two functions (when I remove them everything works). (feebleline-git-branch) (feebleline-project-name). The reason is I do not have proper packages "void-function magit-get-current-branch" and "void-function projectile-project-name".
