### ISSUE TITLE
Documentation missing for feebleline-mode-line-text

### ISSUE THREAD

**Issue by Kungsgeten** [tautologyclub/feebleline#4]
https://github.com/tautologyclub/feebleline/blob/b828b653c120ed2d3f7b283f4858b9e28c39f314/feebleline.el#L85

This is a pretty important variable. It should probably have documentation. I would also suggest to set the variable in the `defvar` sexp. I think by using `setq` it will overwrite user customization, if the customization is done before loading the package (not 100% sure though).

**Comment by tautologyclub** [comment]
I changed it to defvar + setq because reloading didn't work properly with defvar alone. Isn't it better if people customize the variable using eval-after-load, or as a hook, anyway?

**Comment by tautologyclub** [comment]
But the docstring for the defvar is readded now.

**Comment by Kungsgeten** [comment]
I guess that's kind of the purpose; that it shouldn't change when reloading. Even if I use eval-after-load in my init-file, now reloading the library will still overwrite my configuration (I think?). If you want to reload the file, for development purposes or similar, it is possible to visit the file and use `M-x eval-buffer`.

**Comment by tautologyclub** [comment]
I don't think it will overwrite if you do eval-after-load... it certainly won't if you do it as a hook. In any case, it seems like quite a hassle to defvar instead of setq during active development. The docstring is commited and pushed anyway. Leaving issue open temporarily.
