### ISSUE TITLE
Bug toggling `feebleline-mode`.

### ISSUE THREAD

**Issue by jcs090218** [tautologyclub/feebleline#40]
I don't know what is happening but after I toggled certain times of `feebleline-mode` then this appeared.

![Image 1](https://user-images.githubusercontent.com/8685505/60935021-066fec00-a2fb-11e9-91b1-12685582fbef.png)

**Comment by endian-benjamin** [comment]
You mean the modeline? :D Not sure what I'm supposed to see

**Comment by jcs090218** [comment]
Yeah, the modeline! One appeared and the other window remained!

**Comment by tautologyclub** [comment]
Probably related to a setup function getting run async when it expects to be run synchronously.

I don't know, feel free to try to find it but I can't reproduce and it seems like a minor issue to me.

**Comment by jcs090218** [comment]
Okay, I solved it by walk through all windows and manually set `mode-line-format` to something that applied to the current state.

```el
(defun jcs-advice-feebleline-mode-after (&rest _)
    "Advice after execute `feebleline-mode'."
    (if feebleline-mode
        (jcs-walk-through-all-windows-once
         (lambda ()
           (setq mode-line-format nil)))
      (jcs-walk-through-all-windows-once
       (lambda ()
         (setq mode-line-format feebleline--mode-line-format-previous)))))
  (advice-add 'feebleline-mode :after #'jcs-advice-feebleline-mode-after)
```

The easiest way to solve this issue is to walk through all windows and manually set the `mode-line-format` for each window.

**Comment by tautologyclub** [comment]
If you feel like it, you could just put that inside the invocation of feebleline-mode and I'll happily merge it, seems like a fine addition

**Comment by jcs090218** [comment]
This wouldn't be a proper merge because `jcs-walk-through-all-windows-once` function is defined in my own configuration. I will seek for other alternative function that can replace this function.
