### ISSUE TITLE
Wrong project name.

### ISSUE THREAD

**Issue by jcs090218** [tautologyclub/feebleline#47]
If you enter a project then go back to a temporary buffer like `*scratch*`, `*dashboard*`, etc. The project name remained.

**Comment by jcs090218** [comment]
@tautologyclub What do you think about this issue?

**Comment by tautologyclub** [comment]
I don't think this is a correct fix, because if you open, say, a terminal, or the magit status window, then this patch means that you won't display the project name. But if you prefer this behaviour, there's nothing to stop you from keeping the "fixed" version in your init.el.

**Comment by jcs090218** [comment]
I see, you can close this issue if you want to! :D
