### ISSUE TITLE
could each frame have its own feebleline?

### ISSUE THREAD

**Issue by DogLooksGood** [tautologyclub/feebleline#50]
Currently all the frames will have the same feebleline, for example, all feebleline will show the same filename. I think this could be related to those feebleline functions.

**Comment by DogLooksGood** [comment]
I think this could be impossible. looks like one emacs instance can only have one minibuffer

**Comment by endian-benjamin** [comment]
All frames have their own minibuffer. All windows in the same frame share a minibuffer.
