### ISSUE TITLE
feebleline-placeholder should probably be local

### ISSUE THREAD

**Issue by Kungsgeten** [tautologyclub/feebleline#6]
https://github.com/tautologyclub/feebleline/blob/b828b653c120ed2d3f7b283f4858b9e28c39f314/feebleline.el#L145

This variable is only set and used inside a single function. It seems that the variable can be used in a `let`-form inside that function, instead of declaring it as a global variable?

**Comment by tautologyclub** [comment]
True, this is just me not being that comfortable with elisp :) thanks

edit: Having trouble with syntax :(

**Comment by tautologyclub** [comment]
I changed the behaviour somewhat and in the process accomodated both of your withstanding issues. Now feebleline-mode-line-text is composed of dedicated functions so that they can be overriden/modified easily. Clearly much better now. Commit b903bcf5a1d628443aa31cba24fb397998406c52
