### ISSUE TITLE
How to add current time and battery status?

### ISSUE THREAD

**Issue by olegbc1** [tautologyclub/feebleline#7]
Preferably aligned to the right side. Thanks!

**Comment by tautologyclub** [comment]
customize-group feebleline, set feebleline-show-time to t. But it won't be right-aligned. Battery status isn't implemented. Maybe I'll get to it if there's enough interest.

edit: closing this -- if there's interest in battery status, feel free to open a feature request!

**Comment by QiangF** [comment]
You may try awesome-tray
http://www.emacswiki.org/emacs/download/awesome-tray.el
It works very well with the exwm window manager.
