### ISSUE TITLE
Concealing helm modeline

### ISSUE THREAD

**Issue by ghost** [tautologyclub/feebleline#8]
I noticed that the modeline in helm isn't hidden when I open a Helm buffer, and I couldn't find discussion about how to conceal it. To be clear, I'm talking about the bottom modeline that Helm makes that's wedged between the helm buffer and the minbuffer. It's pretty conspicuous in an Emacs frame that's otherwise perfectly, wonderfully modeline-free. There's that thread on Emacs StackExchange that _looks_  like it has something to do with this, which is why I was so confused when I evaluated some of the snippets in that thread, but actually reading the code that I so stupidly evaluated, I realized that they (or maybe I'm just mistaken) were trying to conceal the top modeline above the header.  So back to square one.

Sorry if this is actually a known, easily-amended thing with Helm that I just don't know about. But you probably know how the documentation situation is with Helm, just by sheer nature of being so featureful.

**Comment by tautologyclub** [comment]
I can't say I fully understand what you're trying to say. I'm primarily an Ivy user, but I just tried helm-buffers and I can't see anything wedged between the helm buffer and minibuffer: https://ibb.co/iSa51H

A screenshot would be helpful.

**Comment by ghost** [comment]
Is that so? I've been trying a few different inits, and I honestly cannot figure out how you managed to make that work, but I guess this must be a me issue. Honestly, I feel quite silly coming to you for an issue that's probably more appropriate for Helm, anyways. Sorry for wasting your time.
