### ISSUE TITLE
warning while startup

### ISSUE THREAD

**Issue by Dickby** [tautologyclub/feebleline#9]
with an .emacs that only contains:

```
(package-initialize)
(require 'feebleline)
(feebleline-mode)
```
I get the following warning at startup:
`Warning (bytecomp): reference to free variable ‘ad-do-it’`

I use:
GNU Emacs 27.0.50 (build 41, x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-02-07

**Comment by tautologyclub** [comment]
Yeah I saw that too, if you byte compile you get that warning. ad-do-it is some special elisp form related to either the new or the old advice API. I am pretty sure it's harmless.

**Comment by Dickby** [comment]
I don't bytecompile my .emacs normally, so i get this warning at every emacs startup. It would be nice to get rid of that.

**Comment by DogLooksGood** [comment]
run into the same issue.

**Comment by Dickby** [comment]
I put `(setq ad-do-it nil)` in my early-init.el to silence that warning.

**Comment by DogLooksGood** [comment]
@Dickby thanks, this works!
